# These are supported funding model platforms

github: [PelleNybe] # Replace with your GitHub username if different
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: # Replace with your Ko-fi username
custom: ['https://coraxcolab.com', 'https://cryptop.coraxcolab.com'] # Replace with your custom funding URLs
